In [1]:
import numpy as np
nmaterials = 10

In [2]:
categories_image = np.linspace(0,255, num=nmaterials)
categories_image

array([  0.        ,  28.33333333,  56.66666667,  85.        ,
       113.33333333, 141.66666667, 170.        , 198.33333333,
       226.66666667, 255.        ])

In [5]:
categories_image = [int(x) for x in categories_image]

In [7]:
mapper_image_to_material = {v:i for i,v in enumerate(categories_image)}


In [11]:
pixel = int(round((0.0 + 1.0) * 255) / 2.0))
pixel


128

In [13]:
array = np.array([5,5,8,9,10,3,4,7,8,10])
print(array)
arrayc = np.clip(array, 0,10)
print(arrayc)

[ 5  5  8  9 10  3  4  7  8 10]
[ 5  5  8  9 10  3  4  7  8 10]
